- COMPLIANCE.yaml
- vdyp-common/src/main/java/ca/bc/gov/nrs/vdyp/application/VdypStartApplication.java
- vdyp-common/src/main/java/ca/bc/gov/nrs/vdyp/io/parse/coe/QuadraticMeanDiameterYieldParser.java
- vdyp-common/src/test/java/ca/bc/gov/nrs/vdyp/application/VdypStartApplicationTest.java
- vdyp-common/src/test/java/ca/bc/gov/nrs/vdyp/io/parse/QuadraticMeanDiameterYieldParserTest.java
- vdyp-common/src/test/java/ca/bc/gov/nrs/vdyp/io/parse/value/ValueParserTest.java
- vdyp-common/src/test/java/ca/bc/gov/nrs/vdyp/test/VdypMatchers.java
- vdyp-forward/src/main/java/ca/bc/gov/nrs/vdyp/forward/ForwardProcessingEngine.java
- vdyp-vri/src/main/java/ca/bc/gov/nrs/vdyp/vri/VriStart.java
- vdyp-vri/src/test/java/ca/bc/gov/nrs/vdyp/vri/VriStartTest.java
Pre-process a BATN mode polygon before main processing in VRIStart
> BATN mode for VRIStart

- vdyp-common/src/main/java/ca/bc/gov/nrs/vdyp/common/Utils.java
- vdyp-common/src/test/java/ca/bc/gov/nrs/vdyp/common/UtilsTest.java
Also organized some unit tests in UtilsTest while I was there.
> Fix incorrect initialization of a utilization vector from a single value

- vdyp-tools/src/python/browse_usages.py
- vdyp-tools/src/python/call_tree.py
- vdyp-tools/src/python/commons.py
- vdyp-tools/src/python/util.py
- vdyp-tools/src/python/vdyp-browse-usages.bat
- vdyp-tools/src/python/vdyp-call-tree.bat
- vdyp-tools/src/python/vdyp-commons.bat
The initial drop of the python tools folder, which includes at this point some tools for analyzing the FORTRAN code.
> Adding python tools to source control.

- vdyp-common/src/main/java/ca/bc/gov/nrs/vdyp/application/VdypStartApplication.java
- vdyp-common/src/main/java/ca/bc/gov/nrs/vdyp/common/EstimationMethods.java
- vdyp-common/src/main/java/ca/bc/gov/nrs/vdyp/common/ReconcilationMethods.java
- vdyp-common/src/main/java/ca/bc/gov/nrs/vdyp/common/Utils.java
- vdyp-common/src/main/java/ca/bc/gov/nrs/vdyp/model/UtilizationClass.java
- vdyp-common/src/main/java/ca/bc/gov/nrs/vdyp/model/UtilizationVector.java
- vdyp-common/src/main/java/ca/bc/gov/nrs/vdyp/model/VdypLayer.java
- vdyp-common/src/main/java/ca/bc/gov/nrs/vdyp/model/VdypSpecies.java
- vdyp-common/src/main/java/ca/bc/gov/nrs/vdyp/model/VdypUtilizationHolder.java
- vdyp-common/src/test/java/ca/bc/gov/nrs/vdyp/application/VdypStartApplicationTest.java
- vdyp-common/src/test/java/ca/bc/gov/nrs/vdyp/common/EstimationMethodsTest.java
- vdyp-common/src/test/java/ca/bc/gov/nrs/vdyp/common/ReconcilationMethodsTest.java
- vdyp-fip/src/main/java/ca/bc/gov/nrs/vdyp/fip/FipStart.java
- vdyp-fip/src/test/java/ca/bc/gov/nrs/vdyp/fip/RootFinderTest.java
- vdyp-forward/src/main/java/ca/bc/gov/nrs/vdyp/forward/ForwardProcessingEngine.java
- vdyp-vri/src/main/java/ca/bc/gov/nrs/vdyp/vri/VriStart.java
Creates a UtilizationVector class as a subclass of Coefficients that has direct accessors for utilization classes and accessors indexed using the UtilizationClass enum instead of an integer.
> Add UtilizationVector class

- frontend/src/components/input/species-info/SpeciesListInput.vue
- frontend/src/components/model-param-selection-panes/ReportInfo.vue
- frontend/src/components/model-param-selection-panes/SiteInfo.vue
- frontend/src/components/model-param-selection-panes/SpeciesInfo.vue
- frontend/src/components/model-param-selection-panes/StandDensity.vue
- frontend/src/utils/util.ts
- frontend/src/validation/fileUploadValidation.ts
- frontend/src/validation/fileUploadValidator.ts
- frontend/src/validation/index.ts
- frontend/src/validation/reportInfoValidation.ts
- frontend/src/validation/reportInfoValidator.ts
- frontend/src/validation/siteInfoValidation.ts
- frontend/src/validation/siteInfoValidator.ts
- frontend/src/validation/speciesInfoValidation.ts
- frontend/src/validation/speciesInfoValidator.ts
- frontend/src/validation/standDensityValidation.ts
- frontend/src/validation/standDensityValidator.ts
- frontend/src/views/FileUpload.vue
- File-upload/Input-param Validations and Validators
- parseNumberOrNull util function
> Feature / Frontend File-upload/Input-param Validations and Validators

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/input/file-upload/FileUpload.cy.ts
- frontend/src/components/input/report-info/ReportInfoPanel.cy.ts
- frontend/src/components/input/site-info/SiteInfoPanel.cy.ts
- frontend/src/components/input/site-info/SiteInfoPanel.vue
- frontend/src/components/input/species-info/SpeciesGroupsDisplay.cy.ts
- frontend/src/components/input/species-info/SpeciesInfoPanel.cy.ts
- frontend/src/components/input/species-info/SpeciesInfoPanel.vue
- frontend/src/components/input/species-info/SpeciesListInput.cy.ts
- frontend/src/components/input/stand-density/StandDensityPanel.cy.ts
- frontend/src/components/input/stand-density/StandDensityPanel.vue
- frontend/src/constants/message.ts
- Species-Info-panel component test
- Existing component tests update
> Species-Info-panel Component Test and existing Component Tests update

- frontend/README.md
- frontend/cypress/e2e/unit/validation/fileUploadValidation.cy.ts
- frontend/cypress/e2e/unit/validation/reportInfoValidation.cy.ts
- frontend/cypress/e2e/unit/validation/siteInfoValidation.cy.ts
- frontend/cypress/e2e/unit/validation/speciesInfoValidation.cy.ts
- frontend/cypress/e2e/unit/validation/standDensityValidation.cy.ts
- frontend/cypress/tsconfig.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/input/file-upload/FileUpload.cy.ts
- frontend/src/validation/fileUploadValidator.ts
- frontend/src/validation/reportInfoValidator.ts
- frontend/src/validation/siteInfoValidator.ts
- frontend/src/validation/speciesInfoValidator.ts
- frontend/src/validation/standDensityValidator.ts
- File Upload and Input Model Parameters validation unit tests
- File Upload component updating - add missing test cases
> Frontend/File Upload and Input Model Parameters validation unit tests

- frontend/cypress.config.mjs
- frontend/cypress/e2e/unit/projectionStore.cy.ts
- frontend/cypress/e2e/unit/reportService.cy.ts
- frontend/cypress/tsconfig.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/input/report-info/ReportInfoPanel.cy.ts
- frontend/src/components/input/site-info/SiteInfoPanel.cy.ts
- frontend/src/components/input/site-info/SiteInfoPanel.vue
- frontend/src/components/input/species-info/SpeciesInfoPanel.cy.ts
- frontend/src/components/input/stand-density/StandDensityPanel.cy.ts
- frontend/src/services/reportService.ts
- reportService, projectionStore Unit Test
- Input Model Parameter components updating - add missing test cases
> Frontend: Unit Test #2 - reportService, projectionStore

- frontend/cypress/e2e/unit/modelParameterService.cy.ts
- frontend/cypress/e2e/unit/modelParameterStore.cy.ts
- frontend/package-lock.json
- frontend/package.json
modelParameterService and modelParameterStore unit tests
> Frontend: Unit Test #3 - modelParameterService and modelParameterStore

- frontend/cypress/e2e/unit/apiActions.cy.ts
- frontend/cypress/e2e/unit/apiClient.cy.ts
- frontend/cypress/e2e/unit/apiErrorHandler.cy.ts
- frontend/cypress/e2e/unit/authStore.cy.ts
- frontend/cypress/e2e/unit/reportService.cy.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/constants/message.ts
- frontend/src/services/apiErrorHandler.ts
- apiActions, apiClient, apiErrorHandler, authStore unit tests
- reportService unit test fixes and apiErrorHandler.ts fixes
> Frontend: Unit Test #4

- frontend/src/components/input/file-upload/FileUpload.vue
- frontend/src/constants/constants.ts
- frontend/src/services/apiActions.ts
- frontend/src/services/apiClient.ts
- frontend/src/services/vdyp-api/apis/run-hcsvprojection-api.ts
- frontend/src/stores/projectionStore.ts
- frontend/src/utils/util.ts
- Extract debug text file from zip file returned from API
- Code refactoring - FileUpload
> Frontend/ Projection Request Fields and Parameters Mapping #5

- frontend/cypress/e2e/unit/reportService.cy.ts
- frontend/src/services/modelParameterService.ts
- frontend/src/services/reportService.ts
- frontend/src/services/vdyp-api/models/parameter-names-enum.ts
- frontend/src/views/ModelParameterInput.vue
- Code refactoring - modelParameterService
- Correct reportService.cy.ts and reportService for mocking save and print in unit test
- Remove testing download csv files
> Frontend/ Projection Request Fields and Parameters Mapping #6

- frontend/README.md
- frontend/cypress/e2e/unit/apiActions.cy.ts
- frontend/cypress/e2e/unit/projectionStore.cy.ts
- frontend/src/components/input/file-upload/FileUpload.vue
- frontend/src/components/reporting/ReportingActions.vue
- frontend/src/components/reporting/ReportingContainer.cy.ts
- frontend/src/components/reporting/ReportingContainer.vue
- frontend/src/services/apiActions.ts
- frontend/src/services/apiClient.ts
- frontend/src/services/vdyp-api/apis/run-hcsvprojection-api.ts
- frontend/src/services/vdyp-api/models/parameter-names-enum.ts
- frontend/src/stores/projectionStore.ts
- frontend/src/utils/util.ts
- frontend/src/views/ModelParameterInput.vue
- VDYP-543: Add "Download Raw Results" button on Model Report screen
- Changing parameter names based on changes in the backend
- Make JSON responses acceptable
> VDYP-543: Download Raw Calculation results

- frontend/src/components/input/file-upload/FileUpload.vue
- frontend/src/services/apiActions.ts
- frontend/src/services/apiClient.ts
Add response.status 201 and blob responseType
> Fix: Add response.status 201 and blob responseType

- frontend/src/components/input/file-upload/FileUpload.vue
- frontend/src/components/reporting/ReportingActions.vue
- frontend/src/components/reporting/ReportingContainer.vue
- frontend/src/constants/message.ts
- frontend/src/services/modelParameterService.ts
- frontend/src/utils/util.ts
- frontend/src/views/ModelParameterInput.vue
- Generates a fixed 8-digit random polygon number
- Make the raw results downloadable regardless of the yield table
- Output error messages for results that contain errors
> Frontend: Generates a fixed 8-digit random polygon number

- frontend/README.md
- frontend/package.json
- frontend/src/constants/constants.ts
- frontend/src/services/apiClient.ts
- frontend/src/services/axiosInstance.ts
- frontend/src/services/vdyp-api/apis/run-hcsvprojection-api.ts
- Remove request timeout ( see [https://apps.nrs.gov.bc.ca/int/jira/browse/VDYP-550](url) )
- Set AxiosRequestConfig in projectionHcsvPost only in one place
> VDYP-550: Adjust Request Timeout to Be Handled Solely by HAProxy and Remove Redundant Axios Config

- .github/workflows/openshift-dev.yml
- charts/app/values-dev.yaml
- frontend/src/components/input/attachments/AttachmentsPanel.cy.ts
- frontend/src/components/input/attachments/AttachmentsPanel.stories.ts
- frontend/src/components/input/attachments/AttachmentsPanel.vue
- VDYP-560: Add AttachmentsPanel, component test, and story book
- Set proxy timeout 30min
- Temporarily exclude feature/frontend-VDYP-560 branch deployments to avoid breaking testing because the DEV backend does not work
> VDYP-560: Additional updates required to File Upload and Input Parameters UI (2)

- .github/workflows/openshift-dev.yml
- frontend/src/components/core/AppTabs.vue
- frontend/src/components/input/report-info/ReportInfoPanel.cy.ts
- frontend/src/constants/constants.ts
- frontend/src/constants/message.ts
- frontend/src/views/ModelParameterInput.vue
- Auto-switching to report tab or view error log tab after running model
- ReportInfoPanel component test fix
- Temporarily exclude feature/VDYP-570 branch deployments to avoid breaking testing because the DEV backend does not work
> VDYP-570: Auto-switching to report tab or view error log tab after running model

- .github/workflows/openshift-dev.yml
- .github/workflows/openshift-shared.yml
- .github/workflows/openshift-target-environment.yml
No need to try and build again on test pushes
> VDYP-589: Move Build Logic to the dev workflow only

- .github/workflows/.deployer.yml
- .github/workflows/openshift-dev.yml
PR based workflow doesn't work on dispatch. Also is intentionally overriden to 'latest' currently
> VDYP-589: Move PR based tag to the pull request action

- .github/workflows/prerelease.yml
Fix the reference to the image location
> VDYP-589: Fix the reference to the image repository

- integration-tests/src/test/resources/ca/bc/gov/nrs/vdyp/integration_tests/example_vri/skip
- lib/vdyp-common/src/test/java/ca/bc/gov/nrs/vdyp/application/VdypStartApplicationTest.java
- lib/vdyp-common/src/test/java/ca/bc/gov/nrs/vdyp/io/parse/control/DebugSettingsParserTest.java
- lib/vdyp-common/src/test/java/ca/bc/gov/nrs/vdyp/test/TestUtils.java
- lib/vdyp-forward/src/main/java/ca/bc/gov/nrs/vdyp/forward/ForwardDataStreamReader.java
- lib/vdyp-forward/src/test/java/ca/bc/gov/nrs/vdyp/forward/ForwardProcessorCheckpointGenerationTest.java
- lib/vdyp-forward/src/test/java/ca/bc/gov/nrs/vdyp/forward/ForwardProcessorEndToEndTest.java
- lib/vdyp-forward/src/test/java/ca/bc/gov/nrs/vdyp/forward/ForwardReadPolygonTest.java
- lib/vdyp-forward/src/test/resources/ca/bc/gov/nrs/vdyp/test/vdyp7/vdyp7_output_data.CTR
With conflicts merging into yield table branch resolved: #157
Sorry a few formatter changes that should have been in previous PRs ended up here.
> VDYP-592: Don't try to read growth file if a target age is specified in the VTROL variables

- .github/workflows/.deployer.yml
- .github/workflows/openshift-dev.yml
- .github/workflows/openshift-shared.yml
Enable openshift-dev auto deploy on main push rather than PR events
> VDYP-589 Cleanup  deployer and call sites

- .github/workflows/openshift-dev.yml
- charts/app/values-dev.yaml
- charts/app/values-test.yaml
Reorder and add lib to paths that trigger dev PR build
> VDYP-589: Update min Replicas to 1 on dev and test.

- .github/workflows/openshift-dev.yml
Also Do not bother downloading docker image that we already have
> Vdyp 589 Force builds 

- .github/workflows/openshift-dev.yml
This reverts commit f6de6aac2bfcbb0780f4b91722e41bf7a0f62a65.
> Revert "Remove unecessary docker pull as we just created that image"

- .github/workflows/openshift-dev.yml
Also merge docker step into one
> VDYP-589: Allow workflow dispatch

- .github/workflows/openshift-dev.yml
Add latest with fewer steps to try and match digests in repo
> VDYP-589: SImplify tagging build as latest

- frontend/src/constants/message.ts
- frontend/src/utils/util.cy.ts
- frontend/src/utils/util.ts
- frontend/src/views/ModelParameterInput.vue
- VDYP-698: Disable automatic zip download since download functions now exist for File Upload UI
- VDYP-664: File Naming Convention - Use Report Title and timestamp to provide unique names
- Implemented new cypress unit tests for utils and updated utils.ts
> Feature/VDYP-698 and 664: Disable automatic zip download / Use Report Title for download file name

- frontend/src/components/common/AppConfirmDialog.cy.ts
- frontend/src/components/common/AppConfirmDialog.stories.ts
- frontend/src/components/input/stand-info/StandInfoPanel.cy.ts
- frontend/src/components/input/stand-info/StandInfoPanel.stories.ts
- frontend/src/stores/modelParameterStore.cy.ts
- frontend/src/utils/util.cy.ts
- frontend/src/validation/standInfoValidation.cy.ts
VDYP-691 and 692 : Add components, unit tests and storybook
> Feature/VDYP-691 and 692 : Add components, unit tests and storybook

- frontend/src/components/layout/UserMenu.cy.ts
- frontend/src/components/layout/UserMenu.stories.ts
- frontend/src/components/layout/UserMenu.vue
- frontend/src/services/axiosInstance.ts
- frontend/src/services/keycloak.ts
- frontend/src/stores/common/authStore.cy.ts
- frontend/src/stores/common/authStore.ts
- frontend/src/views/test/AuthInfo.vue
VDYP-729: Authentication Refresh Failure issue fix
> Feature/VDYP-729: Authentication Refresh Failure issue fix

- frontend/src/components/input/site-info/SiteInfoPanel.cy.ts
- frontend/src/components/input/site-info/SiteInfoPanel.vue
- frontend/src/constants/constants.ts
- frontend/src/constants/message.ts
- frontend/src/validation/siteInfoValidation.cy.ts
- frontend/src/validation/siteInfoValidator.ts
- When 'Computed' is selected, the 'Computed' placeholder is displayed in the BHA 50 site index field.
Note: Implemented additional modification requirements for VDYP-662 in the Business Area.
> Feature/VDYP-662 (2)

- .github/workflows/openshift-deploy-crunchy.yml
- charts/app/templates/coms/deployment.yaml
- charts/crunchy-postgres/.helmignore
- charts/crunchy-postgres/Chart.yaml
- charts/crunchy-postgres/README.md
- charts/crunchy-postgres/templates/PostgresCluster.yaml
- charts/crunchy-postgres/templates/_helpers.tpl
- charts/crunchy-postgres/values.yaml
Github action and charts for deploying crunchy PGO to a selected environment. Designed to be run from github in advance of deployments
> VDYP-751: Add Github Action workflow to deploy / update Grunchy PGO 
